apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bkmg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bkmg
    app.kubernetes.io/part-of: tkrw-pr714-0075-0072-app
  name: devfile-sample-bkmg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bkmg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bkmg
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0072-tenant/tkrw-pr714-0075-0072-app/devfile-sample-bkmg@sha256:765a3bf8d6bda9df07a25af5bfaa2c994e2a9412aa3bd7f79b61a811fbaa67d7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
